# Generated by Django 2.1.5 on 2019-04-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailsender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='groups',
            field=models.ManyToManyField(related_name='groups', to='emailsender.Group'),
        ),
    ]
