# Generated by Django 2.1.5 on 2019-04-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailsender', '0005_sentemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='read_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sentemail',
            name='read_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sentemail',
            name='tracker_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
