# Generated by Django 2.1.5 on 2019-04-20 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailsender', '0007_auto_20190418_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_url', models.URLField()),
                ('link_tracking_id', models.CharField(max_length=50, null=True)),
                ('clicked_status', models.BooleanField(default=False)),
                ('clicked_time', models.DateTimeField(null=True)),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emailsender.SentEmail')),
            ],
        ),
    ]
